config/routes.rb
Rails.application.routes.draw do
  get '/robots.:format' => 'pages#robots'
  post 'uploader/image', to: 'uploader#image'
  root 'home#index'
  localized do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
    end
    resources :categories, only: %i[index show]
  end

  scope 'office', module: 'office', as: 'admin' do
    get '', to: 'dashboard#index', as: '/'
    resources :posts, except: :show
    resources :categories, except: :show
    resources :sub_categories, except: :show
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one_attached :main_image
  has_many :category_posts
  has_many :posts, through: :category_posts, inverse_of: 'categories'
  accepts_nested_attributes_for :posts

  has_many :sub_themes_association, class_name: 'SubTheme'
  has_many :sub_themes, through: :sub_themes_association, source: :sub_theme
  has_many :inverse_sub_themes_association, class_name: 'SubTheme', foreign_key: 'sub_theme_id'
  has_many :inverse_sub_themes, through: :inverse_sub_themes_association, source: :category

  scope :displayed, -> { where('published_posts_count > ?', 0) }
  scope :mother, -> { Category.where('id NOT IN (SELECT DISTINCT(sub_theme_id) FROM sub_themes)') }
  scope :children, -> { Category.where('id IN (SELECT DISTINCT(sub_theme_id) FROM sub_themes)') }

=begin
  .where('id NOT IN (SELECT DISTINCT(sub_theme_id) FROM sub_themes)') }
=end

  private

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_one_attached :main_image

  has_many :category_posts
  has_many :categories, through: :category_posts, inverse_of: 'post'
  accepts_nested_attributes_for :categories

  scope :published, -> { where("statut= ?", true ) }

=begin
  after_save :update_counter_cache
  before_destroy :update_counter_cache
=end

=begin
  def update_counter_cache
    self.sub_category.published_posts_count = Post.where("statut= true AND sub_category_id = ?",self.sub_category.id).count
    self.sub_category.save
  end
=end

  private

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  extend FriendlyId
  has_one_attached :main_image
  friendly_id :name, use: :slugged

  scope :displayed, -> { where("published_posts_count > ?" , 0) }

  private

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  before_action :set_categories

  def set_categories
    @nav_categories = Category.mother
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.displayed
  end

  def show
    @category = Category.friendly.find(params[:id])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController #:nodoc:
  before_action :set_post, only: %i[new create]

  def create
    @comment = @post.comments.new(comment_params)

    if @comment.save
      flash.notice = "Commentaire publié"
      redirect_to post_path(@post, anchor: @comment.id)
    else
      flash.alert = "Une erreur est survenue: #{@comment.errors.full_messages.join(', ')}"
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:pseudo, :email, :website, :comment)
  end

  def set_post
    @post = Post.friendly.find(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/office/categories_controller.rb
class Office::CategoriesController < OfficeController
  before_action :category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @sub_themes = @category.sub_themes.build
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.friendly.find(params[:id])
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_path
  end

  private

  def category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(
      :name,
      :description,
      :slug,
      :main_image,
      :meta_robots_index,
      :meta_robots_follow,
      :meta_title,
      :meta_description,
      :meta_image,
      sub_theme_ids:[]
    )
  end

end

app/controllers/office/dashboard_controller.rb
class Office::DashboardController < OfficeController
  def index
  end
end

app/controllers/office/posts_controller.rb
class Office::PostsController < OfficeController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @post.category_posts.build
  end

  def create
    @post = Post.new(post_params)
    @categories = @post.categories.build
    if @post.save
      redirect_to admin_path
    else
      flash.alert = "Une erreur est survenue: #{@post.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :id,
      :title,
      :body,
      :slug,
      :statut,
      :created_at,
      :updated_at,
      :user_id,
      :main_image,
      :meta_image,
      :meta_title,
      :meta_description,
      :meta_robot_index,
      :meta_robot_follow,
=begin
      :category_ids[]
=end
    )
  end
end

app/controllers/office_controller.rb
class OfficeController < ApplicationController
  layout 'admin_layout'
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def robots
    respond_to :text
    expires_in 6.hours, public: true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/uploader_controller.rb
class UploaderController < ApplicationController
  skip_forgery_protection
  def image
    blob = ActiveStorage::Blob.create_after_upload!(
      io: params[:file],
      filename: params[:file].original_filename,
      content_type: params[:file].content_type
    )

    render json: {location: url_for(blob)}, content_type:  "text / html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def robots(index,follow)
    if index == true && follow == false
      'index, nofollow'
    elsif index == false && follow == true
      'noindex, follow'
    else
      "none"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def sub_themes(cat)
    array = []
    cat.sub_themes.each do |sub_cat|
      array.push(name: sub_cat.name, path: category_path(sub_cat.slug))
    end
    return array
  end
end

app/helpers/post_helper.rb
module PostHelper
  def link_if_website(pseudo, url)
    url.present? ? link_to(pseudo, url, rel: 'nofollow') : pseudo
  end
end

app/views/categories/index.html.erb
<% content_for :meta_tags do %>
  <%= render MetaTagsComponent.new(meta_robots_index: true,
                                   meta_robots_follow: true,
                                   meta_title: "",
                                   meta_description: "",
                                   meta_type: "Website",
                                   meta_image: "" ) %>
<% end %>

<h1>Liste des categories</h1>
<ul>
    <% @categories.each do |category| %>
        <li><%= link_to category.name, category_path(category.slug) %> (#<%= category.id %>)</li>
    <% end %>
</ul>

app/views/categories/show.html.erb
<% content_for :meta_tags do %>
  <%= render MetaTagsComponent.new(meta_robots_index: @category.meta_robots_index,
                                   meta_robots_follow: @category.meta_robots_follow,
                                   meta_title: @category.meta_title,
                                   meta_description: @category.meta_description,
                                   meta_type: "Website",
                                   meta_image: (url_for(@category.main_image) if @category.main_image.attached?) ) %>
<% end %>

<%= render HeroComponent.new(category: @category) %>

<article class="container w-100 flex flex-col max-w-5xl mx-auto my-6">
  <nav class="bg-grey-light rounded font-sans w-full">
    <div class="flex text-grey-dark">
      <div><a href="#" class="font-bold">Home</a></div>
      <div><span class="mx-2">></span></div>
      <div><a href="#" class="font-bold">Library</a></div>
      <div><span class="mx-2">></span></div>
      <div>Data</div>
    </div>
  </nav>


  <!--<div class="p-5 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">-->
  <div class="my-6">
    <% @category.posts.each do |post| %>
      <%= render PostCardComponent.new(post: post) %>
    <% end %>
  </div>
</article>

app/views/comments/_form.html.erb
<div  class="bg-gray-50 rounded p-4">
<%= simple_form_for [@post, @post.comments.build],
                    builder: SimpleForm::Tailwind::FormBuilder do |f| %>
  <div>
    <%= f.input :comment, as: :text %>
  </div>
  <div class="grid grid-cols-3 gap-4">
    <%= f.input :pseudo %>
    <%= f.input :email %>
    <%= f.input :website %>
  </div>
  <div class="flex justify-end">
    <%= f.button :submit, "Envoyer", data: { disable_with: "traitement en cours" }, class: "btn btn-submit" %>
  </div>
<% end %>
</div>

app/views/home/index.html.erb
<% content_for :meta_tags do %>
  <%= render MetaTagsComponent.new(meta_robots_index: false,
                                   meta_robots_follow: false,
                                   meta_title: "un Van de nomades",
                                   meta_description: "Un site de passion",
                                   meta_type: "Website",
                                   meta_image: nil) %>
<% end %>

<div class="pt-20 grid">
  <% @categories.each do |category| %>
    <%= link_to category.name, category_path(category.slug) %>
  <% end %>
</div>

app/views/office/categories/_form.html.erb
<%= simple_form_for [:admin,@category] do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :main_image,
              direct_upload: true,
              accept: 'image/png,image/gif,image/jpeg' %>
  <%= f.association :sub_themes, as: :check_boxes, collection: Category.all, input_html: { multiple: true } %>
  <%= tinymce %>
  <%= f.input :description, as: :text, input_html: { class: "tinymce" , rows: 40, cols: 120 } %>
  <%= f.input :slug %>
  <%= f.input :meta_title %>
  <%= f.input :meta_description %>
  <%= f.input :meta_robots_index %>
  <%= f.input :meta_robots_follow %>
  <%= f.submit "Enregister" %>
<% end %>

app/views/office/categories/edit.html.erb
<h1>Edition catégorie :</h1>

<%= render "form" %>

app/views/office/categories/index.html.erb
<h1>Liste des categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>- (#<%= category.id %>)
      <%= link_to "Editer", edit_admin_category_path(category.slug) %> -
      <%= link_to "Supprimer",
                admin_category_path(category.slug),
                :data => { confirm: "Etes vous sur de vouloir supprimer cet article ?" },
                method: :delete %> -
      <%= link_to "Voir", category_path(category.slug) %> </li>
  <% end %>
</ul>

<%= link_to "Ajouter catégorie", new_admin_category_path %>

app/views/office/categories/new.html.erb
<h1>Creation catégorie :</h1>

<%= render "form" %>

app/views/office/dashboard/index.html.erb
<h1>Office::Dashboard#index</h1>
<p>Find me in app/views/office/dashboard/index.html.erb</p>

<%= link_to "Nouvel article", new_admin_post_path %>

app/views/office/posts/_form.html.erb
<%= simple_form_for [:admin,@post] do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :main_image,
              direct_upload: true,
              accept: 'image/png,image/gif,image/jpeg' %>
  <%= tinymce %>
  <%= f.input :body, as: :text, input_html: { class: "tinymce" , rows: 40, cols: 120 } %>
  <%= f.input :slug %>
  <%= f.input :statut %>
  <%= f.input :sub_category_id, collection: @sub_categories %>
  <%= f.date_field :created_at %>
  <%= f.date_field :updated_at %>
  <%= f.input :user_id %>
  <%= f.submit "Enregister" %>
<% end %>

app/views/office/posts/edit.html.erb
<h1>Office::Posts#edit</h1>
<p>Find me in app/views/office/posts/edit.html.erb</p>

<div>
  <%= render 'form' %>
</div>

app/views/office/posts/index.html.erb
<div>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= post.title %> -
        <%= link_to "Editer", edit_admin_post_path(post.id) %> -
        <%= link_to "Supprimer",
                    admin_post_path(post.id),
                    :data => { confirm: "Etes vous sur de vouloir supprimer cet article ?" },
                    method: :delete %> -
        <%= link_to "Voir", post_path(post.id) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/office/posts/new.html.erb
<div>
  <h1>Création d'article</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% content_for :meta_tags do %>
  <%= render MetaTagsComponent.new(meta_robots_index: true,
                                   meta_robots_follow: true,
                                   meta_title: "",
                                   meta_description: "",
                                   meta_type: "Website",
                                   meta_image: "" ) %>
<% end %>

<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post.slug) %> - <%= post.id %></li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<% content_for :meta_tags do %>
  <%= render MetaTagsComponent.new(meta_robots_index: @post.meta_robots_index,
                                   meta_robots_follow: @post.meta_robots_follow,
                                   meta_title: @post.meta_title,
                                   meta_description: @post.meta_description,
                                   meta_type: "Article",
                                   meta_image: (url_for(@post.main_image) if @post.main_image.attached?) ) %>
<% end %>

<article class="mt-20 grid gap-6 max-w-5xl mx-auto m-6 bg-white p-6">
  <h1><%= @post.title %></h1>
  <h2 class="text-2xl"><%#= @post.sub_category.name %></h2>

  <nav class="bg-grey-light rounded font-sans w-full">
    <div class="flex text-grey-dark">
      <div><a href="#" class="font-bold">Home</a></div>
      <div><span class="mx-2">></span></div>
      <div><a href="#" class="font-bold">Library</a></div>
      <div><span class="mx-2">></span></div>
      <div>Data</div>
    </div>
  </nav>

  <% if @post.main_image.attached? %>
    <%= image_tag @post.main_image %>
  <% end %>

  <div class="flex space-x-2">
  <span
    class="
      text-xs
      px-2
      font-medium
      bg-gray-500 bg-opacity-10
      text-gray-800
      rounded
      py-0.5
    "
  >
    Badge
  </span>
    <span
      class="
      text-xs
      px-2
      font-medium
      bg-red-500 bg-opacity-10
      text-red-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>

    <span
      class="
      text-xs
      px-2
      font-medium
      bg-yellow-500 bg-opacity-10
      text-yellow-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>
    <span
      class="
      text-xs
      px-2
      font-medium
      bg-green-500 bg-opacity-10
      text-green-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>

    <span
      class="
      text-xs
      px-2
      font-medium
      bg-blue-500 bg-opacity-10
      text-blue-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>
    <span
      class="
      text-xs
      px-2
      font-medium
      bg-purple-500 bg-opacity-10
      text-purple-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>
    <span
      class="
      text-xs
      px-2
      font-medium
      bg-indigo-500 bg-opacity-10
      text-indigo-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>
    <span
      class="
      text-xs
      px-2
      font-medium
      bg-pink-500 bg-opacity-10
      text-pink-800
      rounded
      py-0.5
    "
    >
    Badge
  </span>
  </div>

  <div class="rich-text">
    <%= @post.body.html_safe %>
  </div>

  <div class="grid grid-cols-2">
    <h3><%= @post.comments_count %> <%= @post.comments_count <= 1 ? "commentaire" : "commentaires" %></h3>
    <%= link_to "Laisser un commentaire", post_path(:anchor => "form"), class: 'link text-right' %>
  </div>


  <h3 class="text-xl">Rejoindre la discussion :</h3>
  <%= render CommentsComponent.new(post: @post) %>


  <div>
    <%= render "comments/form" %>
  </div>
</article>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>